// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://azboyppmhiwdtdrzhsoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6Ym95cHBtaGl3ZHRkcnpoc296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODc0NDYsImV4cCI6MjA2Njg2MzQ0Nn0.UvPLtpdK7Lq-1FNWwHbouPJ4KxGLKFfuLQRzIT50d0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);